# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntrip.proto\"\xc1\x01\n\x04Trip\x12\x0f\n\x07trip_id\x18\x01 \x01(\x05\x12\x11\n\tdriver_id\x18\x02 \x01(\x05\x12\x10\n\x08rider_id\x18\x03 \x01(\x05\x12\x0c\n\x04\x63ity\x18\x04 \x01(\t\x12\"\n\x0cvehicle_type\x18\x05 \x01(\x0e\x32\x0c.VehicleType\x12\x0c\n\x04\x66\x61re\x18\x06 \x01(\x02\x12\x13\n\x0b\x64istance_km\x18\x07 \x01(\x02\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\x12\x1b\n\x06status\x18\t \x01(\x0e\x32\x0b.TripStatus\"!\n\tTripBatch\x12\x14\n\x05trips\x18\x01 \x03(\x0b\x32\x05.Trip*F\n\nTripStatus\x12\r\n\tREQUESTED\x10\x00\x12\x0b\n\x07ONGOING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\r\n\tCANCELLED\x10\x03*3\n\x0bVehicleType\x12\x08\n\x04\x42IKE\x10\x00\x12\x08\n\x04\x41UTO\x10\x01\x12\x07\n\x03\x43\x41\x42\x10\x02\x12\x07\n\x03SUV\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRIPSTATUS']._serialized_start=245
  _globals['_TRIPSTATUS']._serialized_end=315
  _globals['_VEHICLETYPE']._serialized_start=317
  _globals['_VEHICLETYPE']._serialized_end=368
  _globals['_TRIP']._serialized_start=15
  _globals['_TRIP']._serialized_end=208
  _globals['_TRIPBATCH']._serialized_start=210
  _globals['_TRIPBATCH']._serialized_end=243
# @@protoc_insertion_point(module_scope)
